version: "3.8"

services:
  db-logistica:
    image: postgres:16.2
    container_name: "containerBancoDeDadosLogistica"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    restart: always
  app-logistica:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app-sistema-logistica
    environment:
      POSTGRES_HOST: db-logistica:5432
    ports:
      - "8082:8082"
    depends_on:
      - db-logistica
    restart: always