version: "3.8"

services:
  db-logistica:
    image: postgres:16.2
    hostname: db-logistica
    container_name: "containerBancoDeDadosLogistica"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./../scriptBancoDeDados:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'containerRabbitMQ'
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - db-logistica
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  app-logistica:
    build:
      context: ./../
      dockerfile: Dockerfile
    container_name: app-sistema-logistica
    environment:
      POSTGRES_HOST: db-logistica:5432
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    restart: always
